---
path: .
memory: 1G
stack: cflinuxfs2
buildpack: python_buildpack
env:
  NEW_RELIC_CONFIG_FILE: /home/vcap/app/newrelic.ini
  NEW_RELIC_LOG: stdout
  WEB_CONCURRENCY: 4
services:
  - fec-api-search
