---
inherit: manifest_base.yml
host: fec-feature-api
services:
  - fec-creds-feature
  - fec-redis-feature
  - fec-s3-feature
env:
  NEW_RELIC_APP_NAME: fec | api | feature
  NEW_RELIC_ENV: feature
applications:
  - name: celery-worker
    instances: 1
    memory: 512M
    command: celery worker --app webservices.tasks --loglevel INFO --concurrency 2
