---
inherit: manifest_dev.yml
env:
  NEW_RELIC_APP_NAME: fec | celery beat | dev
- name: celery-beat
  instances: 1
  memory: 256M
  no-route: true
  health-check-type: process
  command: celery beat --app webservices.tasks
