---
inherit: manifest_dev.yml
env:
  NEW_RELIC_APP_NAME: fec | celery worker | dev
applications:
  - name: celery-worker
    instances: 1
    memory: 1G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel INFO --concurrency 2