---
inherit: manifest_stage.yml
env:
  NEW_RELIC_APP_NAME: fec | celery worker | stage
- name: celery-worker
  instances: 1
  memory: 1G
  no-route: true
  health-check-type: process
  command: celery worker --app webservices.tasks --loglevel INFO --concurrency 2